name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        branch: docs
        folder: out/html
        config_file: docs/Doxyfile
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}